version: '3'
services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
    networks:
      - proyecto_base_net

networks:
  proyecto_base_net:
    external: true
